export const mockLevels = [
  {
    id: '10000000-0000-4000-8000-000000000001',
    slug: 'a2',
    cefr: 'A2',
    title: 'Foundations',
    description: 'Build essential grammar, vocabulary and everyday communication skills.',
    order_index: 1,
    illustration_url: null,
    status: 'published',
  },
  {
    id: '10000000-0000-4000-8000-000000000002',
    slug: 'b1',
    cefr: 'B1',
    title: 'Independent English',
    description: 'Communicate confidently about work, travel, experiences and everyday life.',
    order_index: 2,
    illustration_url: null,
    status: 'published',
  },
] as const

export const mockModules = [
  {
    id: '20000000-0000-4000-8000-000000000001',
    level_id: mockLevels[0].id,
    slug: 'everyday-foundations',
    title: 'Everyday foundations',
    description: 'Handle common situations with clear and useful English.',
    learning_outcome: 'Introduce yourself, make plans and manage everyday conversations.',
    illustration_url: null,
    icon: 'message-circle',
    order_index: 1,
    estimated_minutes: 95,
    is_required: true,
    status: 'published',
  },
  {
    id: '20000000-0000-4000-8000-000000000002',
    level_id: mockLevels[0].id,
    slug: 'past-and-plans',
    title: 'Past and plans',
    description: 'Talk about completed events and future intentions.',
    learning_outcome: 'Describe past experiences and explain what you plan to do next.',
    illustration_url: null,
    icon: 'calendar-days',
    order_index: 2,
    estimated_minutes: 110,
    is_required: true,
    status: 'published',
  },
  {
    id: '20000000-0000-4000-8000-000000000003',
    level_id: mockLevels[1].id,
    slug: 'experiences-and-stories',
    title: 'Experiences and stories',
    description: 'Connect events and share experiences with more detail.',
    learning_outcome: 'Tell coherent stories and discuss experiences naturally.',
    illustration_url: null,
    icon: 'book-open',
    order_index: 1,
    estimated_minutes: 120,
    is_required: true,
    status: 'published',
  },
  {
    id: '20000000-0000-4000-8000-000000000004',
    level_id: mockLevels[1].id,
    slug: 'work-and-opinions',
    title: 'Work and opinions',
    description: 'Explain ideas and take part in practical discussions.',
    learning_outcome: 'Express opinions, give reasons and communicate confidently at work.',
    illustration_url: null,
    icon: 'briefcase-business',
    order_index: 2,
    estimated_minutes: 130,
    is_required: true,
    status: 'published',
  },
] as const

export const mockLessons = [
  {
    id: '30000000-0000-4000-8000-000000000001',
    module_id: mockModules[0].id,
    slug: 'introductions',
    title: 'Introductions that feel natural',
    description: 'Introduce yourself and keep a first conversation going.',
    order_index: 1,
    estimated_minutes: 16,
    is_required: true,
    status: 'published',
    version: 1,
  },
  {
    id: '30000000-0000-4000-8000-000000000002',
    module_id: mockModules[0].id,
    slug: 'daily-routines',
    title: 'Daily routines',
    description: 'Describe regular activities and ask about another person’s day.',
    order_index: 2,
    estimated_minutes: 18,
    is_required: true,
    status: 'published',
    version: 1,
  },
  {
    id: '30000000-0000-4000-8000-000000000003',
    module_id: mockModules[1].id,
    slug: 'weekend-stories',
    title: 'Weekend stories',
    description: 'Talk about past events in a clear sequence.',
    order_index: 1,
    estimated_minutes: 20,
    is_required: true,
    status: 'published',
    version: 1,
  },
  {
    id: '30000000-0000-4000-8000-000000000004',
    module_id: mockModules[2].id,
    slug: 'talking-about-experiences',
    title: 'Talking about experiences',
    description: 'Build vocabulary for memorable life experiences.',
    order_index: 1,
    estimated_minutes: 18,
    is_required: true,
    status: 'published',
    version: 1,
  },
  {
    id: '30000000-0000-4000-8000-000000000005',
    module_id: mockModules[2].id,
    slug: 'present-perfect-essentials',
    title: 'Present perfect essentials',
    description: 'Connect past experiences to the present.',
    order_index: 2,
    estimated_minutes: 22,
    is_required: true,
    status: 'published',
    version: 1,
  },
  {
    id: '30000000-0000-4000-8000-000000000006',
    module_id: mockModules[2].id,
    slug: 'a-life-changing-trip',
    title: 'A life-changing trip',
    description: 'Read a short story and identify its key details.',
    order_index: 3,
    estimated_minutes: 20,
    is_required: true,
    status: 'published',
    version: 1,
  },
  {
    id: '30000000-0000-4000-8000-000000000007',
    module_id: mockModules[2].id,
    slug: 'listening-to-experiences',
    title: 'Listening to experiences',
    description: 'Follow a conversation about travel and personal change.',
    order_index: 4,
    estimated_minutes: 20,
    is_required: true,
    status: 'published',
    version: 1,
  },
  {
    id: '30000000-0000-4000-8000-000000000008',
    module_id: mockModules[2].id,
    slug: 'module-review',
    title: 'Module review',
    description: 'Review the vocabulary, grammar, reading and listening skills from this module.',
    order_index: 5,
    estimated_minutes: 25,
    is_required: true,
    status: 'published',
    version: 1,
  },
  {
    id: '30000000-0000-4000-8000-000000000009',
    module_id: mockModules[3].id,
    slug: 'sharing-opinions',
    title: 'Sharing opinions',
    description: 'State an opinion and support it with clear reasons.',
    order_index: 1,
    estimated_minutes: 19,
    is_required: true,
    status: 'published',
    version: 1,
  },
] as const

export const mockLessonBlocks = [
  {
    id: '40000000-0000-4000-8000-000000000011',
    lesson_id: mockLessons[3].id,
    type: 'intro',
    title: 'Your goal',
    content: { body: 'Learn practical words for describing memorable life experiences.' },
    order_index: 1,
    is_required: true,
    is_graded: false,
  },
  {
    id: '40000000-0000-4000-8000-000000000012',
    lesson_id: mockLessons[3].id,
    type: 'vocabulary',
    title: 'Experience vocabulary',
    content: {
      items: [
        { term: 'memorable', definition: 'worth remembering', example: 'It was a memorable trip.' },
        {
          term: 'challenging',
          definition: 'difficult in an interesting way',
          example: 'Learning to dive was challenging.',
        },
        {
          term: 'achievement',
          definition: 'something you succeed in doing',
          example: 'Finishing the race was an achievement.',
        },
        {
          term: 'opportunity',
          definition: 'a good chance to do something',
          example: 'It was an opportunity to travel.',
        },
      ],
    },
    order_index: 2,
    is_required: true,
    is_graded: false,
  },
  {
    id: '40000000-0000-4000-8000-000000000013',
    lesson_id: mockLessons[3].id,
    type: 'single_choice',
    title: 'Choose the best word',
    content: {
      prompt: 'Completing my first marathon was a big ___.',
      options: ['achievement', 'opportunity', 'journey'],
      hint: 'Choose the word for something you succeeded in doing.',
    },
    order_index: 3,
    is_required: true,
    is_graded: true,
  },
  {
    id: '40000000-0000-4000-8000-000000000014',
    lesson_id: mockLessons[3].id,
    type: 'summary',
    title: 'Key idea',
    content: { body: 'Use specific words to make descriptions clearer and more personal.' },
    order_index: 4,
    is_required: true,
    is_graded: false,
  },
  {
    id: '40000000-0000-4000-8000-000000000021',
    lesson_id: mockLessons[4].id,
    type: 'grammar',
    title: 'Present perfect',
    content: {
      explanation: 'Use have or has followed by the past participle.',
      formula: 'subject + have / has + past participle',
      examples: ['I have visited Japan.', 'She has never tried surfing.'],
    },
    order_index: 1,
    is_required: true,
    is_graded: false,
  },
  {
    id: '40000000-0000-4000-8000-000000000022',
    lesson_id: mockLessons[4].id,
    type: 'fill_gap',
    title: 'Complete the sentence',
    content: {
      prompt: 'She ___ never tried surfing.',
      placeholder: 'Type one word',
      hint: 'Use the third-person form of have.',
    },
    order_index: 2,
    is_required: true,
    is_graded: true,
  },
  {
    id: '40000000-0000-4000-8000-000000000023',
    lesson_id: mockLessons[4].id,
    type: 'multiple_choice',
    title: 'Choose both correct sentences',
    content: {
      prompt: 'Which sentences use the present perfect correctly?',
      options: [
        'I have visited Rome twice.',
        'She has finished the course.',
        'We have went to Spain.',
      ],
    },
    order_index: 3,
    is_required: true,
    is_graded: true,
  },
  {
    id: '40000000-0000-4000-8000-000000000031',
    lesson_id: mockLessons[5].id,
    type: 'reading',
    title: 'A life-changing trip',
    content: {
      body: 'Two years ago, Maya volunteered in Costa Rica. Since then, she has become more independent and has made friends from five countries.',
    },
    order_index: 1,
    is_required: true,
    is_graded: false,
  },
  {
    id: '40000000-0000-4000-8000-000000000032',
    lesson_id: mockLessons[5].id,
    type: 'reading_question',
    title: 'Check your understanding',
    content: {
      prompt: 'What has changed for Maya?',
      options: [
        'She has become more independent.',
        'She has stopped travelling.',
        'She has moved permanently.',
      ],
    },
    order_index: 2,
    is_required: true,
    is_graded: true,
  },
  {
    id: '40000000-0000-4000-8000-000000000041',
    lesson_id: mockLessons[6].id,
    type: 'listening',
    title: 'A conversation about change',
    content: {
      instructions: 'Read the transcript as a listening simulation.',
      transcript:
        'Leo: What was the most challenging part? Nina: Speaking English every day, but it became easier after the first week.',
    },
    order_index: 1,
    is_required: true,
    is_graded: false,
  },
  {
    id: '40000000-0000-4000-8000-000000000042',
    lesson_id: mockLessons[6].id,
    type: 'listening_question',
    title: 'Listen for detail',
    content: {
      prompt: 'What was most challenging for Nina?',
      options: ['Speaking English every day', 'Finding a place to stay', 'Travelling alone'],
    },
    order_index: 2,
    is_required: true,
    is_graded: true,
  },
  {
    id: '40000000-0000-4000-8000-000000000051',
    lesson_id: mockLessons[7].id,
    type: 'intro',
    title: 'Module review',
    content: { body: 'Complete the final quiz to check the skills from this module.' },
    order_index: 1,
    is_required: true,
    is_graded: false,
  },
  {
    id: '40000000-0000-4000-8000-000000000052',
    lesson_id: mockLessons[7].id,
    type: 'quiz',
    title: 'Final quiz',
    content: {
      prompt: 'Choose one answer for every question.',
      questions: [
        {
          prompt: 'Which word means worth remembering?',
          options: ['memorable', 'challenging', 'ordinary'],
        },
        { prompt: 'Complete: I ___ visited Italy twice.', options: ['have', 'has', 'am'] },
        {
          prompt: 'What has Maya become?',
          options: ['More independent', 'Less confident', 'More isolated'],
        },
        {
          prompt: 'What challenged Nina?',
          options: ['Speaking English', 'The weather', 'Her job'],
        },
        {
          prompt: 'Which sentence is correct?',
          options: [
            'She has never tried surfing.',
            'She have never tried surfing.',
            'She has never try surfing.',
          ],
        },
      ],
    },
    order_index: 2,
    is_required: true,
    is_graded: true,
  },
] as const

export const mockAnswerKeys: Record<string, string | string[]> = {
  '40000000-0000-4000-8000-000000000013': 'achievement',
  '40000000-0000-4000-8000-000000000022': 'has',
  '40000000-0000-4000-8000-000000000023': [
    'I have visited Rome twice.',
    'She has finished the course.',
  ],
  '40000000-0000-4000-8000-000000000032': 'She has become more independent.',
  '40000000-0000-4000-8000-000000000042': 'Speaking English every day',
  '40000000-0000-4000-8000-000000000052': [
    'memorable',
    'have',
    'More independent',
    'Speaking English',
    'She has never tried surfing.',
  ],
}

export const mockLevelProgress = [
  {
    level_id: mockLevels[0].id,
    completion_percent: 100,
    average_accuracy: 91,
    assessment_score: 88,
    status: 'completed',
  },
  {
    level_id: mockLevels[1].id,
    completion_percent: 42,
    average_accuracy: 84,
    assessment_score: null,
    status: 'in_progress',
  },
] as const

export const mockModuleProgress = [
  {
    module_id: mockModules[0].id,
    completion_percent: 100,
    average_accuracy: 92,
    assessment_score: 90,
    status: 'completed',
  },
  {
    module_id: mockModules[1].id,
    completion_percent: 100,
    average_accuracy: 89,
    assessment_score: 87,
    status: 'completed',
  },
  {
    module_id: mockModules[2].id,
    completion_percent: 38,
    average_accuracy: 84,
    assessment_score: null,
    status: 'in_progress',
  },
  {
    module_id: mockModules[3].id,
    completion_percent: 0,
    average_accuracy: null,
    assessment_score: null,
    status: 'available',
  },
] as const

export const mockLessonProgress = [
  {
    lesson_id: mockLessons[0].id,
    completion_percent: 100,
    accuracy_percent: 94,
    status: 'completed',
    last_activity_at: '2026-08-18T12:00:00.000Z',
  },
  {
    lesson_id: mockLessons[1].id,
    completion_percent: 100,
    accuracy_percent: 90,
    status: 'completed',
    last_activity_at: '2026-08-19T12:00:00.000Z',
  },
  {
    lesson_id: mockLessons[2].id,
    completion_percent: 100,
    accuracy_percent: 88,
    status: 'completed',
    last_activity_at: '2026-08-20T12:00:00.000Z',
  },
  {
    lesson_id: mockLessons[3].id,
    completion_percent: 62,
    accuracy_percent: 84,
    status: 'in_progress',
    last_activity_at: '2026-08-21T12:00:00.000Z',
  },
] as const
